Bundle\ProjectBundle\Entity\PlacePhotos:
    type: entity
    table: place_photos
    repositoryClass: Bundle\ProjectBundle\Entity\Repository\PlacePhotosRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        placeId:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: place_id
        imgRef:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: img_ref
        imgUrl:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: img_url
        origin:
            type: string
            length: 20
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
