Bundle\ProjectBundle\Entity\Places:
    type: entity
    table: places
    repositoryClass: Bundle\ProjectBundle\Entity\Repository\PlacesRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        extId:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: ext_id
        slug:
            type: string
            length: 255
            fixed: false
            nullable: false
        detailsRef:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: details_ref
        origin:
            type: string
            length: 20
            fixed: false
            nullable: false
        hasOwner:
            type: integer
            unsigned: false
            nullable: false
            column: has_owner
    
    oneToMany:
        reviews:
            targetEntity: Bundle\ProjectBundle\Entity\PlaceReviews
            mappedBy: places
    oneToMany:
        comments:
            targetEntity: Bundle\ProjectBundle\Entity\Comment
            mappedBy: place
    oneToOne:
        placeDetails:
            targetEntity: Bundle\ProjectBundle\Entity\PlaceDetails
            mappedBy: place        
#    oneToOne:
#        placeDetails:
#            targetEntity: Bundle\ProjectBundle\Entity\PlaceDetails
#            cascade: {  }
#            mappedBy: null
#            inversedBy: null
#            joinColumns:
#                    id:
#                    referencedColumnName: place_id
#            orphanRemoval: false  
#    manyToOne:
#        place:
#            targetEntity: Places
#            cascade: {  }
#            mappedBy: null
#            inversedBy: null
#            joinColumns:
#                place_id:
#                    referencedColumnName: id
#            orphanRemoval: false
#    oneToOne:
#        placeDetails:
#            targetEntity: Bundle\ProjectBundle\Entity\PlaceDetails
#            joinColumns:
#                    id:
#                    referencedColumnName: place_id
#            orphanRemoval: false

#    oneToOne:
#        placeDetails:
#            targetEntity: Bundle\ProjectBundle\Entity\PlaceDetails
#            mappedBy: null
#            inversedBy: null
#            joinColumns:
#                    id:
#                    referencedColumnName: place_id
#            joinColumn:
#                    name: id
#                    referencedColumnName: place_id
            
    lifecycleCallbacks: {  }
