Bundle\ProjectBundle\Entity\PlaceTypes:
    type: entity
    table: place_types
    repositoryClass: Bundle\ProjectBundle\Entity\Repository\PlaceTypesRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        placeId:
            type: integer
            unsigned: false
            nullable: false
            column: place_id
        typeId:
            type: integer
            unsigned: false
            nullable: false
            column: type_id
        main:
            type: string
            length: 255
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
