Bundle\ProjectBundle\Entity\Types:
    type: entity
    table: types
    repositoryClass: Bundle\ProjectBundle\Entity\Repository\TypesRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        type:
            type: string
            length: 255
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
