## Home page YAML Template.

#Preload method
preLoad:
    pattern:  /
    defaults: { _controller: BundleProjectBundle:Page:preLoad }
        
#MAIN/HOME page
index:
    pattern: /home
    defaults: { _controller: BundleProjectBundle:Page:index }
    requirements:
      _method: GET
index_indexShowPlace:
    pattern:  /home/{name}
    defaults: { _controller: BundleProjectBundle:Page:indexShowPlace }
    requirements:
        _method:  GET
        
index_placeDetails:
    pattern: /home/details/{name}
    defaults: { _controller: BundleProjectBundle:Page:placeDetails }
