## Login YAML Template.
login:
    path:   /login
    defaults: { _controller: BundleProjectBundle:Auth:login }

logout:
    path:   /logout
    defaults: { _controller: EcoUserBundle:Auth:logout }

login_check:
    path:  /login_check
    defaults: { _controller: EcoUserBundle:Auth:loginCheck }
