Bundle\PlacesBundle\Entities\Categories:
    type: entity
    table: categories
    repositoryClass: Bundle\PlacesBundle\Entities\Repository\CategoriesRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        category:
            type: string
            length: 255
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
