Bundle\PlacesBundle\Entities\Ownership:
    type: entity
    table: ownership
    repositoryClass: Bundle\PlacesBundle\Entities\Repository\OwnershipRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 45
            fixed: false
            nullable: false
            column: name
     
        email:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: email
        tel:
            type: string
            nullable: false
            column: phonenumber
            
        verify:
            type: integer
            nullable: true
            column: validationUser
            
        placeId:
            type: integer
            unsigned: false
            nullable: false
            column: place_id
           
       
    lifecycleCallbacks: {  }
