Bundle\PlacesBundle\Entities\Places:
    type: entity
    table: places
    repositoryClass: Bundle\PlacesBundle\Entities\Repository\PlacesRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        extId:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: ext_id
        slug:
            type: string
            length: 255
            fixed: false
            nullable: false
        detailsRef:
            type: string
            #length: 300
            fixed: false
            nullable: false
            column: details_ref
        origin:
            type: string
            length: 20
            fixed: false
            nullable: false
        hasOwner:
            type: integer
            unsigned: false
            nullable: false
            column: has_owner
    
    oneToMany:
        reviews:
            targetEntity: Bundle\PlacesBundle\Entities\PlaceReviews
            mappedBy: places
    oneToMany:
        comments:
            targetEntity: Bundle\PlacesBundle\Entities\Comment
            mappedBy: place
    oneToOne:
        placeDetails:
            targetEntity: Bundle\PlacesBundle\Entities\PlaceDetails
            mappedBy: place        
    lifecycleCallbacks: {  }
