Bundle\PlacesBundle\Entities\PlaceTags:
    type: entity
    table: place_tags
    repositoryClass: Bundle\PlacesBundle\Entities\Repository\PlaceTagsRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        placeId:
            type: integer
            unsigned: false
            nullable: false
            column: place_id
        tagId:
            type: integer
            unsigned: false
            nullable: false
            column: tag_id
        main:
            type: string
            length: 255
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
