Bundle\PlacesBundle\Entities\PlaceCategories:
    type: entity
    table: place_categories
    repositoryClass: Bundle\PlacesBundle\Entities\Repository\PlaceCategoriesRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        placeId:
            type: integer
            unsigned: false
            nullable: false
            column: place_id
        categoryId:
            type: integer
            unsigned: false
            nullable: false
            column: category_id
    lifecycleCallbacks: {  }
