<?php

namespace Bundle\PlacesBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AppUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppUsersRepository extends EntityRepository
{
}
