<?php

namespace Bundle\PlacesBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsersIpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersIpRepository extends EntityRepository
{
    public function getUserHits($ip) {
        $qb = $this->createQueryBuilder('user')
                        ->select('user.count')
                        ->where('user.ip = :ip')
                        ->setParameter(':ip', $ip)
                        ->getQuery()->getResult();
        if (!empty($qb)) {
            return $qb[0]['count'];
        }
    }

    public function getTotalUniqueUsers() {
        $qb = $this->createQueryBuilder('user')
                ->select('user.id')
                ->getQuery()
                ->getResult();
        return count($qb);
    }
    
    public function isUser($ip) {
        $qb = $this->createQueryBuilder('user')
                ->select('user.ip')
                ->where('user.ip = :ip AND user.voteFlag = 1')
                ->setParameter('ip', $ip)
                ->getQuery()
                ->getResult();
        $row_count = count($qb);
        if($row_count == 1) {
            return true;
        }else {
            return false;
        }
    }
    
    public function updateClient($ip) {
        $qb = $this->createQueryBuilder('')
                ->update('Bundle\PlacesBundle\Entity\UsersIp','u')
                ->set('u.voteFlag', ':flag')
                ->where('u.ip = :ip')
                ->setParameter('flag', 1)
                ->setParameter('ip', $ip);
        
        return $qb->getQuery()->execute();
                
    }
}
