<?php

namespace Proxies\__CG__\Bundle\PlacesBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Places extends \Bundle\PlacesBundle\Entity\Places implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setExtId($extId)
    {
        $this->__load();
        return parent::setExtId($extId);
    }

    public function getExtId()
    {
        $this->__load();
        return parent::getExtId();
    }

    public function setSlug($slug)
    {
        $this->__load();
        return parent::setSlug($slug);
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }

    public function setDetailsRef($detailsRef)
    {
        $this->__load();
        return parent::setDetailsRef($detailsRef);
    }

    public function getDetailsRef()
    {
        $this->__load();
        return parent::getDetailsRef();
    }

    public function setOrigin($origin)
    {
        $this->__load();
        return parent::setOrigin($origin);
    }

    public function getOrigin()
    {
        $this->__load();
        return parent::getOrigin();
    }

    public function setHasOwner($hasOwner)
    {
        $this->__load();
        return parent::setHasOwner($hasOwner);
    }

    public function getHasOwner()
    {
        $this->__load();
        return parent::getHasOwner();
    }

    public function addComment(\Bundle\PlacesBundle\Entity\Comment $comments)
    {
        $this->__load();
        return parent::addComment($comments);
    }

    public function removeComment(\Bundle\PlacesBundle\Entity\Comment $comments)
    {
        $this->__load();
        return parent::removeComment($comments);
    }

    public function getComments()
    {
        $this->__load();
        return parent::getComments();
    }

    public function setPlaceDetails(\Bundle\PlacesBundle\Entity\PlaceDetails $placeDetails = NULL)
    {
        $this->__load();
        return parent::setPlaceDetails($placeDetails);
    }

    public function getPlaceDetails()
    {
        $this->__load();
        return parent::getPlaceDetails();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'extId', 'slug', 'detailsRef', 'origin', 'hasOwner', 'placeDetails', 'comments');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}