# *
# _bundle_project:
#      resource: "@BundlePlacesBundle/Resources/config/routing/routing.yml"
#social sign-in
testToken:
  path: /testToken
  defaults: { _controller:BundlePlacesBundle:Auth:testToken }

clear:
  path: /clear
  defaults: { _controller:BundlePlacesBundle:Auth:clear }

## Login YAML Template.

## Home page
_bundle_places_home:
  resource: "@BundlePlacesBundle/Resources/config/routing/home.yml"
    
## About page
_bundle_places_about:
  resource: "@BundlePlacesBundle/Resources/config/routing/about.yml"

## Render place actions
_bundle_places_renderPlace:
  resource: "@BundlePlacesBundle/Resources/config/routing/render-place.yml"

## Posts, comm. actions
_bundle_places:
  resource: "@BundlePlacesBundle/Resources/config/routing/forms-posts.yml"
  
_bundle_places_services:
  resource: "@BundlePlacesBundle/Resources/config/routing/services.yml"  

_bundle_places_admin:
  resource: "@BundlePlacesBundle/Resources/config/routing/login.yml"