security:
    encoders:
        Bundle\ProjectBundle\Entity\AppUsers:
            algorithm:        md5
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: BundleProjectBundle:AppUsers, property: txtLogin }
    firewalls:
            login:
                pattern:  ^/admin/login$
                security: false
            testToken:
                pattern:  ^/testToken$
                security: false
            
            admin_area:
                pattern:   ^/
                form_login:
                    login_path: login
                    check_path: login_check
                    always_use_default_target_path: true
                    default_target_path: admin_start
                anonymous: true
                logout:
                    path:   logout
                    target: login
                remember_me:
                    key:      "%secret%"
                    lifetime: 31536000 # 365 days in seconds
                    path:     /
                    domain:   ~


    access_control:
        - { path: ^/admin, roles: ROLE_USER }


## Symfony2 default demo security schema
#security:
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#
#    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
#
#    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        login:
#            pattern:  ^/demo/secured/login$
#            security: false
#
#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: _security_check
#                login_path: _demo_login
#            logout:
#                path:   _demo_logout
#                target: _demo
#            #anonymous: ~
#            #http_basic:
#            #    realm: "Secured Demo Area"
#
#    access_control:
#        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
#        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
