parameters:
#    bundle_project.example.class: Bundle\ProjectBundle\Example

#services:
#    model.storemodel:
#      class: Bundle\ProjectBundle\Model\StoreModel
#      arguments: 
#        entityManager: "@doctrine.orm.entity_manager"
#    bundle_project.example:
#        class: %bundle_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
