## Forms-Posts YAML Template.

# Forms Controller & Comm. controller
#Create comment route
comment_create:
    pattern:  /comment/{place_id}
    defaults: { _controller: BundlePlacesBundle:Comment:create }
    requirements:
        _method:  POST
        store_id: \d+
        
#Search by rating route
search:
    pattern:  /places/search
    defaults: { _controller: BundlePlacesBundle:Forms:search }
    requirements:
        _method:  POST
        
#Vote - POST REQUESTS
votee:
    pattern:  /votee
    defaults: { _controller: BundlePlacesBundle:Forms:votee }
    requirements:
        _method:  POST
setVote:
    pattern:  /setVote
    defaults: { _controller: BundlePlacesBundle:Forms:setVote }
    requirements:
        _method:  POST
morePlacesRequest:
    pattern:  /morePlacesRequest
    defaults: { _controller: BundlePlacesBundle:Forms:morePlacesRequest }
#    requirements:
#        _method:  POST       
demoSearch:
    pattern:  /demoSearch
    defaults: { _controller: BundlePlacesBundle:Forms:demoSearch }
    requirements:
        _method:  POST|GET
        
#autocom_ac:
#    pattern: /autocomaction
#    defaults: { _controller: BundlePlacesBundle:Forms:doAutocom }
    
autocom_places:
    pattern: /placesnames
    defaults: { _controller: BundlePlacesBundle:Forms:getPlacesNames } 
    
insert_places:
    pattern: /insertplaces
    defaults: { _controller: BundlePlacesBundle:Forms:insertPlaces }   
    
insert_homepage_places:
    pattern: /homepageplaces
    defaults: { _controller: BundlePlacesBundle:Forms:homepagePlaces }    
#    requirements:
#      _method: POST         
