## Home page YAML Template.

#Preload method
preLoad:
    pattern:  /
    defaults: { _controller: BundlePlacesBundle:Page:preLoad }
        
#MAIN/HOME page
index:
    pattern: /home
    defaults: { _controller: BundlePlacesBundle:Page:index }
    requirements:
      _method: GET
index_indexShowPlace:
    pattern:  /home/{name}
    defaults: { _controller: BundlePlacesBundle:Page:indexShowPlace }
    requirements:
        _method:  GET
        
index_placeDetails:
    pattern: /home/details/{name}
    defaults: { _controller: BundlePlacesBundle:Page:placeDetails }    
    
eventUploadPhoto:
    path: /eventUploadPhoto
    defaults: { _controller: BundlePlacesBundle:Events:eventuploaduhoto }
    
eventdetails:
    path: /eventDetails
    defaults: { _controller: BundlePlacesBundle:Page:eventsDetails }    
   # methods:  [POST]
#    requirements:
#        id:  \d+