## Places YAML Template.

# Render place
renderPlace:
    pattern:  /renderPlace/{param}/{search}
    defaults: { _controller: BundlePlacesBundle:Forms:renderPlace, search: ma }
    requirements:
        _method:  GET
