
search_name:
    pattern: /searchname/{name}
    defaults: { _controller: BundlePlacesBundle:Service:searchByName }
    requirements:
      _method: GET
    
search_address:
    pattern: /searchaddress/{address}
    defaults: { _controller: BundlePlacesBundle:Service:searchByAddress }
    requirements:
      _method: GET
      
search_tag:
    pattern: /searchtag/{tag}
    defaults: { _controller: BundlePlacesBundle:Service:searchByTag }
    requirements:
      _method: GET  
      
search_tag_addr:
    pattern: /searchtagaddr/{tag}/{address}
    defaults: { _controller: BundlePlacesBundle:Service:searchByTagAndAddress }
    requirements:
      _method: GET  
      
search:
    pattern: /searchplace/{input}/{food}/{drink}
    defaults: { _controller: BundlePlacesBundle:Service:search, food:off, drink:off }
    requirements:
      _method: GET  
      
homepage_places:
    pattern: /homeplace
    defaults: { _controller: BundlePlacesBundle:Service:homepagePlaces }
    requirements:
      _method: GET       
      
search_add:
    pattern: /searchaddress/{input}
    defaults: { _controller: BundlePlacesBundle:Service:searchAddress }
    requirements:
      _method: GET       
      
test_search_name:
    pattern: /testsearchname
    defaults: { _controller: BundlePlacesBundle:Service:testService }
    requirements:
      _method: GET   
      
autocom:
    pattern: /autocom
    defaults: { _controller: BundlePlacesBundle:Service:autocom }
    requirements:
      _method: GET  
      
#autocom_ac:
#    pattern: /autocomaction
#    defaults: { _controller: BundlePlacesBundle:Service:doAutocom }
#    requirements:
#      _method: POST      
