<?php

namespace Bundle\PlacesBundle\Entities\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceReviewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceReviewsRepository extends EntityRepository
{
    function getReviewsById($id){
        $qb = $this->createQueryBuilder('reviews')
                ->select('reviews')
                ->where('reviews.places = :id')
                ->setParameter('id', $id);
        
        return $qb->getQuery()->getResult();
    }
    
    // Check for place reviews
    function checkForPlaceReviews($id){
        $qb = $this->createQueryBuilder('reviews')
                ->select('reviews')
                ->where('reviews.places = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->getResult();
                
        $rows = count($qb);
        if($rows >= 1){
            return true;
        }else{
            return false;
        }
    }
    
    // Get reviews for place
    function getReviews($id){
        $qb = $this->createQueryBuilder('review')
                ->select('review.author, review.authorUrl, review.review, review.ratingAspect, review.rating, review.date')
                ->where('review.places = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->getResult();
        return $qb;
    }
    
    // Delete reviews for a place from place_reviews
    public function deletePlceReviews($id){
        
        $em = $this->getEntityManager();
        //echo "in delete";
        $query = $em
        ->createQuery("
                DELETE 
                FROM Bundle\PlacesBundle\Entities\PlaceReviews pr
                WHERE pr.places = :id
            ")
        ->setParameter('id',$id);

        return $query;
    }
}
