<?php

namespace Bundle\ProjectBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceTypesRepository extends EntityRepository
{
    // out of date
    public function idTypeCombination($id, $idType){
        $qb = $this->createQueryBuilder('type')
                ->select('type.id')
                ->where('type.placeId = :id')
                ->andWhere('type.typeId = :idType')
                ->setParameter('id', $id)
                ->setParameter('idType', $idType)
                ->getQuery()
                ->getResult();
        
        if (count($qb)>=1) {
            return true;
        } else {
            return false;
        }
        
    }
    
    // is place in place_types tb
    public function isPlaceInserted($id){
        $qb = $this->createQueryBuilder('type')
                ->select('type.id')
                ->where('type.placeId = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->getResult();
        
        if (count($qb)>=1) {
            return true;
        } else {
            return false;
        }
    }
    
    // Delete places from place_types
    public function deletePlaces($id){
        
        $em = $this->getEntityManager();

        $query = $em
        ->createQuery("
                DELETE 
                FROM Bundle\ProjectBundle\Entity\PlaceTypes pt
                WHERE pt.placeId = :id
            ")
        ->setParameter('id',$id);

        return $query;
    }
}
