<?php

namespace Bundle\ProjectBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsRepository extends EntityRepository
{
    public function getTagId($tag){
        $qb = $this->createQueryBuilder('tags')
                ->select('tags.id')
                ->where('tags.tag = :tag')
                ->setParameter('tag', $tag)
                ->getQuery()
                ->getResult();
        if (count($qb) == 1) {      
            return $qb;
        } else {
            return false;
        }
    }
    
    public function isTag($tag){
        $qb = $this->createQueryBuilder('tags')
                ->select('tags.id')
                ->where('tags.tag = :tag')
                ->setParameter('tag', $tag)
                ->getQuery()
                ->getResult();
        if (count($qb) >= 1){
            return true;
        } else {
            return false;
        }
    }
    
    // Get all types
    public function getAllTags(){
        $qb = $this->createQueryBuilder('tags')
                ->select('tags.id,tags.tag');
                
        return $qb->getQuery()->getResult();
    }
}
