<?php

namespace Bundle\ProjectBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypesRepository extends EntityRepository
{
    public function getTypeId($type){
        $qb = $this->createQueryBuilder('types')
                ->select('types.id')
                ->where('types.type = :type')
                ->setParameter('type', $type)
                ->getQuery()
                ->getResult();
        if (count($qb) == 1) {      
            return $qb;
        } else {
            return false;
        }
    }
    
    public function isType($type){
        $qb = $this->createQueryBuilder('types')
                ->select('types.id')
                ->where('types.type = :tag')
                ->setParameter('tag', $type)
                ->getQuery()
                ->getResult();
        if (count($qb) >= 1){
            return true;
        } else {
            return false;
        }
    }
    
    // Get all types
    public function getAllTypes(){
        $qb = $this->createQueryBuilder('types')
                ->select('types.id,types.type');
                
        return $qb->getQuery()->getResult();
    }
}
