<?php

namespace Proxies\__CG__\Bundle\ProjectBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AppUsers extends \Bundle\ProjectBundle\Entity\AppUsers implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'txtLogin', 'txtPassword', 'txtEmail', 'booActive', 'timeStamp');
        }

        return array('__isInitialized__', 'id', 'txtLogin', 'txtPassword', 'txtEmail', 'booActive', 'timeStamp');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AppUsers $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxtLogin($txtLogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxtLogin', array($txtLogin));

        return parent::setTxtLogin($txtLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxtLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxtLogin', array());

        return parent::getTxtLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxtPassword($txtPassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxtPassword', array($txtPassword));

        return parent::setTxtPassword($txtPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxtPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxtPassword', array());

        return parent::getTxtPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxtEmail($txtEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxtEmail', array($txtEmail));

        return parent::setTxtEmail($txtEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxtEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxtEmail', array());

        return parent::getTxtEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setBooActive($booActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBooActive', array($booActive));

        return parent::setBooActive($booActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getBooActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBooActive', array());

        return parent::getBooActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeStamp($timeStamp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimeStamp', array($timeStamp));

        return parent::setTimeStamp($timeStamp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeStamp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimeStamp', array());

        return parent::getTimeStamp();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', array($serialized));

        return parent::unserialize($serialized);
    }

}
