<?php

namespace Proxies\__CG__\Bundle\ProjectBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PlaceDetails extends \Bundle\ProjectBundle\Entity\PlaceDetails implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'placeId', 'placeName', 'placePhonenumber', 'placeVicinity', 'placeLat', 'placeLng', 'placeRating', 'placeIcon', 'placeUrl', 'placeWebsite');
        }

        return array('__isInitialized__', 'id', 'placeId', 'placeName', 'placePhonenumber', 'placeVicinity', 'placeLat', 'placeLng', 'placeRating', 'placeIcon', 'placeUrl', 'placeWebsite');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PlaceDetails $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceId($placeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceId', array($placeId));

        return parent::setPlaceId($placeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceId', array());

        return parent::getPlaceId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceName($placeName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceName', array($placeName));

        return parent::setPlaceName($placeName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceName', array());

        return parent::getPlaceName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlacePhonenumber($placePhonenumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlacePhonenumber', array($placePhonenumber));

        return parent::setPlacePhonenumber($placePhonenumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlacePhonenumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlacePhonenumber', array());

        return parent::getPlacePhonenumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceVicinity($placeVicinity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceVicinity', array($placeVicinity));

        return parent::setPlaceVicinity($placeVicinity);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceVicinity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceVicinity', array());

        return parent::getPlaceVicinity();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceLat($placeLat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceLat', array($placeLat));

        return parent::setPlaceLat($placeLat);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceLat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceLat', array());

        return parent::getPlaceLat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceLng($placeLng)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceLng', array($placeLng));

        return parent::setPlaceLng($placeLng);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceLng()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceLng', array());

        return parent::getPlaceLng();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceRating($placeRating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceRating', array($placeRating));

        return parent::setPlaceRating($placeRating);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceRating', array());

        return parent::getPlaceRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceIcon($placeIcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceIcon', array($placeIcon));

        return parent::setPlaceIcon($placeIcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceIcon', array());

        return parent::getPlaceIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceUrl($placeUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceUrl', array($placeUrl));

        return parent::setPlaceUrl($placeUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceUrl', array());

        return parent::getPlaceUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceWebsite($placeWebsite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceWebsite', array($placeWebsite));

        return parent::setPlaceWebsite($placeWebsite);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceWebsite', array());

        return parent::getPlaceWebsite();
    }

}
