parameters:
    placeoperation.class: Bundle\PlacesBundle\Service\PlaceOperations
    placeoperationDAO.class: Bundle\PlacesBundle\Service\PlaceOperationsDAO
    test.class: Bundle\PlacesBundle\Service\Test

#    bundle_project.example.class: Bundle\ProjectBundle\Example

#services:
#    model.storemodel:
#      class: Bundle\ProjectBundle\Model\StoreModel
#      arguments: 
#        entityManager: "@doctrine.orm.entity_manager"
#    bundle_project.example:
#        class: %bundle_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    test:
        class: Bundle\PlacesBundle\Service\Test
        
    monolog.formatter.session_request:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%channel%%.%%level_name%%: %%message%%\n"    
    placeop:
        class: Bundle\PlacesBundle\Service\PlaceOperations
        arguments: [@placeopDAO, @service_container, @logger]
        tags:
            - { name: monolog.logger, channel: comm }
    placeopDAO:
        class: "%placeoperationDAO.class%"   
        arguments: [@doctrine.orm.entity_manager]
        
    search:
        class: Bundle\PlacesBundle\Service\SearchWebService
        arguments: [@searchDAO, @service_container]
        tags:
            - { name: monolog.logger, channel: comm }
    searchDAO:
        class: Bundle\PlacesBundle\Service\SearchWebServiceDAO  
        arguments: [@doctrine.orm.entity_manager]    
        
    formsop:
        class: Bundle\PlacesBundle\Service\FormsOperations  
        arguments: [@formsdao, @service_container, @insertalldetails, @placeop, @placeopDAO, @insertplace]
  
    formsdao:
        class: Bundle\PlacesBundle\Service\FormsOperationsDAO  
        arguments: [@doctrine.orm.entity_manager]
        
    insertalldetails:
        class: Bundle\PlacesBundle\Command\InsertAllDetailsCommand 
        arguments: [ @placeop, @insertphotos, @insertrev, @insertadet ]   
        
    insertadet:
        class: Bundle\PlacesBundle\Command\InsertPlacesDetailsCommand 
        arguments: [ @placeop ] 
        
    insertrev:
        class: Bundle\PlacesBundle\Command\InsertPlaceReviewsCommand 
        arguments: [ @placeop ] 
        
    insertphotos:
        class: Bundle\PlacesBundle\Command\InsertPlacesPhotosCommand 
        arguments: [ @placeop ] 
        
    insertplace:
        class: Bundle\PlacesBundle\Command\InsertPlacesCommand 
        arguments: [ @placeop ]  
        
    insertallinone:
        class: Bundle\PlacesBundle\Command\InsertPlaceAllInOneCommand
        arguments: [ @placeop, @insertalldetails ]     
        
        