Bundle\PlacesBundle\Entities\AppUsers:
    properties:
        username:  
            - NotBlank: ~
        password:
            - NotBlank: { groups: [registration] }
            - Length: { min: 8, groups: [registration] }
        email:   
            - Email: { groups: [registration] }            
        timeStamp:
            - DateTime: ~
            
Bundle\PlacesBundle\Entities\UsersIp:
    properties:
        ip:
            - Ip: ~
        count:
            - Range:
                min: 0
                minMessage: must be at least 0
        voteFlag:  
            - Range:
                min: 0
                max: 1
                minMessage: must be at least 0
                maxMessage: can't be over 1
                
Bundle\PlacesBundle\Entities\VoteStatus:
    properties:
        placeId:
            - NotBlank: ~
        userIp:
            - Ip: ~
            
Bundle\PlacesBundle\Entities\Tags:
    properties:
        tag:
           - NotBlank: ~
           
Bundle\PlacesBundle\Entities\Places:
    properties:
        extId:
            - NotBlank: ~
            - Length:
                max: 255
                maxMessage: "extId cannot be longer than {{ limit }} characters length"
        slug:
            - NotBlank: ~
            - Length:
                max: 255
        detailsRef:
            - NotBlank: ~
#            - Length:
#                max: 300
        origin:
            - NotBlank: ~
            - Length:
                max: 20
        hasOwner:
            - Range:
                min: 0
                max: 1
                minMessage: must be at least 0
                maxMessage: can't be over 1
                
Bundle\PlacesBundle\Entities\PlaceTags:
    properties:
        placeId:
            - NotBlank: ~
            - Range:
                min: 0
        tagId:
            - NotBlank: ~
            - Range:
                min: 0
        main:
            - Choice:
                choices:  [true, false]
                
Bundle\PlacesBundle\Entities\PlaceReviews:
    properties:
        author:
            - NotBlank: ~
            - Length:
                max: 255
        authorUrl:   
            - Url: ~
        review:
            - Length:
                max: 1000
        ratingAspect:
            - NotBlank: ~
            - Length:
                max: 30
        rating:
            - Range:
                min: 0
                max: 5
                minMessage: must be at least 0
                maxMessage: can't be over 5
        date: 
            - NotBlank: ~
            - Length:
                max: 100
                
Bundle\PlacesBundle\Entities\PlaceRatings:
    properties:
        placeId:
            - NotBlank: ~
            - Range:
                min: 0
        totalVotes: 
            - NotBlank: ~
        votesCount:    
            - NotBlank: ~
            
Bundle\PlacesBundle\Entities\PlacePhotos:
    properties:
        placeId:
            - NotBlank: ~
            - Range:
                min: 0
        imgRef:        
            - NotBlank: ~
        imgUrl:
            - Url: ~ 
        origin:
            - NotBlank: ~
            - Length:
                max: 20
                
Bundle\PlacesBundle\Entities\PlaceDetails:
    properties:
       placeId:
            - NotBlank: ~
            - Range:
                min: 0
       placeName: 
           - NotBlank: ~
           - Length:
                max: 255
       placePhonenumber: 
           - Length:
                max: 20
       placeVicinity:
           - NotBlank: ~
           - Length:
                max: 255
       placeLat:
           - NotBlank: ~
           - Length:
                max: 100
       placeLng:
           - NotBlank: ~
           - Length:
                max: 100
       placeRating:
           - Length:
                max: 3
       placeIcon:
           - Url: ~
       placeUrl:
           - Url: ~
       placeWebsite:    
           - Url: ~
           
Bundle\PlacesBundle\Entities\Comment:
    properties:
        user:
           - NotBlank: ~
           - Length:
                max: 100 
        approved: 
            - Choice:
                choices:  [0, 1]
        created:    
           - DateTime: ~ 
        updated:   
           - DateTime: ~
        comment:
           - NotBlank: ~ 
 
            
Bundle\PlacesBundle\Entities\PlaceEvents:
 properties:
#        image:
#            - Url: ~
        image:
            - Url: ~